apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 3000       # The port within the cluster
      targetPort: 3000 # The port on the container
      nodePort: 32000  # The port on the node (externally accessible)
  type: NodePort