# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 3000       # the port that the service will expose
      targetPort: 3000 # the port on the container to which the traffic will be directed
  type: LoadBalancer